version: "3"
services:
  reverseproxy:
      image: ceofvo/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: ceofvo/udagram-api-user
    volumes:
      - "%UserProfile%\.aws":/root/.aws
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_HOST: ${POSTGRES_HOST} 
      AWS_REGION: ${AWS_REGION}
      AWS_PROFILE: ${AWS_PROFILE} 
      AWS_BUCKET: ${AWS_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: "http://localhost:8100"
  backend-feed:
    image: ceofvo/udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: ceofvo/udacity-frontend
    ports:
      - "8100:80"